= Name Construction (Plants)

Plant names are governed by the http://www.iapt-taxon.org/nomen/main.php?page=title[International Code Of Nomenclature
For Algae, Fungi, and Plants]

We construct names from name parts in the NSL using the rank and the name parents. This document is meant to describe
our understanding of the name construction process for different types of names. The Types of names we currently build
for Plant names are:

* scientific
  - binomial
  - polynomial
  - mononomial
  - hybrid
  - hybrid formula
  - autonym
* cultivar
  - hybrid
* informal
* common

== Scientific names

scientific names are constructed differently depending on the name types:

* hybrid formula
* autonym
* not formula or autonym i.e. just scientific.

We construct a simple name and a full name. The simple name is the full name without the author.

Names are constructed from:

. preceding name
. rank
. name element
. author
. manuscript marker

in that order.

The different parts are optional and depend on a number of conditions outlined in the following sections.

=== preceding name

A preceding name is used in polynomial names (most commonly binomial names like Genus Species).
The preceding name it the simple name (no author) of the Name Parent.

A name has a parent if it is ranked below Genus.

Each name has a name parent. At the moment the name parent is the name directly above the name normally according to the
publication the name is in. It is a name that can participate in name construction, or a preceding name.

The preceding name is found by finding the parent rank of the names' rank, and following the name parent id up until
you find the name with that rank. The parent ranks below family are currently set as per the following table:

|===
| Rank | Parent Rank

|Familia|
|Subfamilia|Familia
|Tribus|Familia
|Subtribus|Familia
|Genus| [none, monomial]
|Subgenus|Genus
|Sectio|Genus
|Subsectio|Genus
|Series|Genus
|Subseries|Genus
|Superspecies|Genus
|Species|Genus
|Subspecies|Species
|Nothovarietas|Species
|Varietas|Species
|Subvarietas|Species
|Forma|Species
|Subforma|Species
|form taxon|Species
|morphological var.|Species
|nothomorph.|Species
|[infrafamily]|Familia
|[infraspecies]|Species
|[infragenus]|Genus

|===

As you can see this can be expressed as:

[source]
.parentRank
----
parentRank(rank) {
    if(rank >= Genus) return none // we don't care above Genus
    if(rank >= Species) return Genus
    //now the infas
    if(rank == [infraspecies]) return Species
    if(rank == [infragenus]) return Genus
}
----

but it is better to use the database rank records for configurability and readability, e.g.

[source]
.parentRank
----
parentRank = rank.parentRank
----

Because there will never be more than a couple of names between the name and its' preceding name we use this pseudo code
to find the preceding name:

[source,groovy]
.getPreviousName.groovy
----
Name getPreviousName(Name name) {
    if(name.rank >= Genus) return null
    Rank parentRank = name.rank.parentRank
    Name prev = name.parent
    while (prev && prev.rank < parentRank) {
        prev = prev.parent
    }
    if(prev.rank = parentRank) {
        return prev
    }
    return null
}
----

==== hybrid formula

The preceding name for a hybrid formula name is the name parent.

=== Rank



