= Tree Placement and Editing Rules
v1.0, March 2018
:imagesdir: resources/images/
:toc: left
:toclevels: 4
:toc-class: toc2
:icons: font
:iconfont-cdn: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css
:stylesdir: resources/style/
:stylesheet: asciidoctor.css
:description: New tree structure documentation
:keywords: documentation, NSL, APNI, API, APC, tree
:links:
:numbered:

Placing taxa on a tree has a set of rules that need to be understood. This document attempts to explain them.

== Previous documentation

* https://www.anbg.gov.au/25jira/browse/NSL-464[JIRA - NSL-464]
* https://www.anbg.gov.au/ibis25/display/NSL/Tree+Monitor+Functionality[Confluence - Tree Monitor Functionality]
* NewTreeStucture.adoc

The JIRA NSL-464 lists the rules as:

*Prevent placement for:*

1. Within any classification, the placement of name on the tree must be below the rank of the name of its parent node.

2. Within any classification, the placement of a name at the level of species and below must be within a branch subtended by the node, at rank genus, using the same generic name.

3. Similarly, the placement of a name below the rank of species must be within the branch subtending from its species.

4. Placement of an instance within a classification is not permitted if there is already an instance node bearing the
same name within that tree.

*Warning should be issued (at least) for:*

5. Placement of an instance within a classification should not be permitted if there exists a node for an instance that
places the new instance name in synonymy; unless, all synonymic instances of that name within the tree, bear the
pro_parte qualification.

6. Placement of an instance within a classification should not be permitted if its synonyms include the name of an
instance that already exists within the tree; unless, the synonymic instance bears the pro_parte qualification.

7. Placement of an instance within a classification should not be permitted if its synonyms include the name of a
synonym of an instance that already exists within the tree; unless, all synonymic instance bear the pro_parte
qualification.

In part these rules are *incorrect* or deficient. Below I am documenting what has been implemented in code after much
discussion and testing with users.

== The code

A summary of what we check can be found by looking at the code for placing a new taxon on the tree:

[source:groovy]
.Validate New Element Placement groovy
----
    protected List<String> validateNewElementPlacement(TreeVersionElement parentElement, TaxonData taxonData) {

       TreeVersion treeVersion = parentElement.treeVersion

(1)    List<String> warnings = checkNameValidity(taxonData)

       NameRank taxonRank = NameRank.findByName(taxonData.rank)
       NameRank parentRank = NameRank.findByName(parentElement.treeElement.rank)

       //is rank below parent
(2)    if (!RankUtils.rankHigherThan(parentRank, taxonRank)) {
           throw new BadArgumentsException("Name $taxonData.simpleName of rank $taxonRank.name is not below rank $parentRank.name of $parentElement.treeElement.simpleName.")
       }

       //polynomials must be placed under parent
(3)    checkPolynomialsBelowNameParent(taxonData.simpleName, taxonData.excluded, taxonRank, parentElement.namePath.split('/'))

(4)    checkInstanceIsNotOnTheTree(taxonData, treeVersion)
(5)    checkNameIsNotOnTheTree(taxonData, treeVersion)
(6)    checkNameNotAnExistingSynonym(taxonData, treeVersion, [])
(7)    checkSynonymsOfNameNotOnTheTree(taxonData, treeVersion)
(8)    checkSynonymsAreNotSynonymsOnTheTree(taxonData, treeVersion, [])

       return warnings
    }

----

We describe each test below.

=== Check name validity (warning only)

ACTION: Warn that you are placing an invalid name.

The creates a warning if the name is *nom Illeg* or *nom Inval*. It does not stop you from adding the name.

=== Check the rank of the name is below it's parent

ACTION: Prevents the taxon being placed.

You can't place a lower rank above a higher one in the tree.

=== Check a polynomial name is below it's parent name

ACTION: Prevents the taxon being placed.

e.g. Doodia aspera must be placed below Doodia not Woodwardia because the name is *Doodia* aspera not *Woodwardia* aspera.

=== Check if the instance is already on the tree

ACTION: Prevents the taxon being placed.

Checks if the instance of the taxon is already placed on the tree. It will prevent the taxon being
placed. In general you can replace an instance, but not with itself, so you would have to remove the existing instance
first before placing it again, but this is almost always not what you want to do... [because??]

=== check Name Is Not On The Tree

ACTION: Prevents the taxon being placed.

Checks if the name of the taxon is already placed on the tree. You need to replace the accepted taxon.
In general this shouldn't happen because the editor prevents it.

=== check Name Not An Existing Synonym

ACTION: Prevents the taxon being placed.

Checks if the name of the taxon being placed is a synonym of name already placed as accepted on the tree. If so, you
need to supersede the accepted taxon or modify its synonymy.

Error example: Can’t place this concept - Angophora costata subsp. leiocarpa is in synonymy under accepted concept
Angophora leiocarpa (L.A.S.Johnson ex G.J.Leach) K.R.Thiele & LadigesCHAH (2006), Australian Plant Census.

=== check Synonyms Of Name Not On The Tree

ACTION: Prevents the taxon being placed.

This checks if any of the synonyms of the taxon you are placing is a name already placed on the tree as an accepted taxon.
If so, you need to supersede the accepted taxon.

Error example: Can’t place this concept - synonym is accepted concept Angophora costata subsp. euryphylla L.A.S.Johnson
ex G.J.LeachCHAH (2006), Australian Plant Census

=== check Synonyms Are Not Synonyms On The Tree

ACTION: Prevents the taxon being placed.

This checks if any of the synonyms of the taxon you are placing is also a synonym of an accepted name already placed on
the tree. If so, you need to supersede the accepted name or modify its synonymy.

Error example: Can’t place this concept - synonym Eucalyptus gigantea is also a synonym of Eucalyptus globulus Labill.CHAH
(2006), Australian Plant Census

== Synonym errors

=== candidate name is an accepted name

e.g. trying to place another concept of Doodia aspera:

Can't place this concept - Doodia aspera is already accepted as
Doodia aspera R.Br.CHAH (2014), Australian Plant Census

=== candidate's synonym is an accepted name

e.g. trying to place a concept that has Doodia aspera as a synonym:

Can't place this concept - synonym Doodia aspera (R.Br.) Mett. is an accepted concept
Doodia aspera R.Br.CHAH (2014), Australian Plant Census


=== candidate name is a synonym of an accepted name

e.g. trying to place a concept of Woodwardia aspera:

Can't place this concept - Woodwardia aspera (R.Br.) Mett. is part of accepted concept
Doodia aspera R.Br.CHAH (2014), Australian Plant Census

=== cadidates's synonym is a synonym of an accepted name

e.g. trying to place a concept (other than Doodia aspera) that has Woodwardia aspera as a synonym:

Can't place this concept - synonym Woodwardia aspera (R.Br.) Mett. is part of accepted concept
Doodia aspera R.Br.CHAH (2014), Australian Plant Census

== Fixup edits

We need to be able to edit past annotations and possibly synonomy that have been erroneously entered. These minor edits
are considered errata to a published tree (see https://www.anbg.gov.au/25jira/browse/NSL-2550[NSL-2550]).

.From NSL-2550 Kirsten Cowley
----
    We would like the following to be included in "minor edits":
    1. deletion or edit of distribution
    2. deletion or edit of comment
    3. addition of a basionym
    4. addition of autonyms
    5. addition of orthographic variants
    6. addition of isonyms

    We do not consider any of these to be a change of concept and therefore do not need a new instance.

    We like the idea of having to provide a reason for the change and would like to suggest the following:
    1. Change in distribution
    2. Comment deleted
    3. Comment edited
    4. Basionym added
    5. Autonym added
    6. Orthographic variant added
    7. Isonym added
----

Presenting the User Interface for making a fix like these needs to be consistent across the types of change and obvious
that you are changing the historical data.

Accessing the historical data such as the Distribution and Comment data in the editor will potentially be a challenge as
they may be stored in older versions. We currently only edit the current version and a draft. It would be logical to use
previously used instances as the vector to the previous versions in the editor, as that works in a similar way to the
previous use of Instance Notes to provide this information.

icon:question-circle[2x, role='yellow'] | Not an immediate problem, but: How do we handle other attributes people may need to edit for different trees?
