package au.org.biodiversity.nsl

import java.sql.Timestamp

/**
 * User: pmcneil
 * Date: 8/01/18
 *
 */
class TreeTstHelper {

    static List<TreeElement> makeTestElements(TreeVersion version, List<Map> elementData, List<Map> tveData) {
        List<TreeElement> elements = []
        Map<Long, Long> generatedIdMapper = [:]
        elementData.each { Map data ->
            data.remove('previousElementId')
            TreeElement e = new TreeElement(data)
            e.save()
            generatedIdMapper.put(data.id as Long, e.id as Long)
            elements.add(e)
        }
        Timestamp now = new Timestamp(System.currentTimeMillis())
        Map<String, String> elementLinkMapper = [:]
        tveData.each { Map data ->

            TreeVersionElement tve = new TreeVersionElement(data)
            tve.treeVersion = version
            tve.treeElement = TreeElement.get(generatedIdMapper.get(data.treeElementId as Long) as Long)
            tve.elementLink = "http://localhost:7070/nsl-mapper/tree/$version.id/$data.treeElementId"
            tve.treePath = filterTreePath(generatedIdMapper, data.treePath)
            tve.parent = TreeVersionElement.get(elementLinkMapper[data.parentId])
            tve.updatedBy = 'tester'
            tve.updatedAt = now
            elementLinkMapper.put(data.elementLink, tve.elementLink)
            tve.save()
        }

        version.save(flush: true)
        version.refresh()
        return elements
    }

    private static filterTreePath(Map idMap, String treePath) {
        if (idMap.isEmpty()) {
            println "ID Map is empty!!!!!!!!"
        }
        idMap.each { k, v ->
            treePath = treePath.replaceAll("/$k", "/$v")
        }
        return treePath
    }


    static Map doodiaElementData = [
            id               : 9788223,
            lockVersion      : 0,
            displayHtml      : "<data><scientific><name id='70914'><element class='Doodia'>Doodia</element> <authors><author id='1441' title='Brown, R.'>R.Br.</author></authors></name></scientific><citation>Parris, B.S. in McCarthy, P.M. (ed.) (1998), Doodia. <i>Flora of Australia</i> 48</citation></data>",
            excluded         : false,
            instanceId       : 578615,
            instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/578615",
            nameElement      : "Doodia",
            nameId           : 70914,
            nameLink         : "http://localhost:7070/nsl-mapper/name/apni/70914",
            previousElementId: null,
            profile          : ["APC Dist.": ["value": "NT, SA, Qld, NSW, LHI, NI, ACT, Vic, Tas", "created_at": "2008-08-06T00:00:00+10:00", "created_by": "BRONWYNC", "updated_at": "2008-08-06T00:00:00+10:00", "updated_by": "BRONWYNC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1105068"], "APC Comment": ["value": "<i>Doodia</i> R.Br. is included in <i>Blechnum</i> L. in NSW.", "created_at": "2016-06-10T15:22:41.742+10:00", "created_by": "blepschi", "updated_at": "2016-06-10T15:23:01.201+10:00", "updated_by": "blepschi", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/6842406"]],
            rank             : "Genus",
            simpleName       : "Doodia",
            sourceElementLink: null,
            sourceShard      : "APNI",
            synonyms         : null,
            synonymsHtml     : "<synonyms></synonyms>",
            updatedAt        : "2018-01-01 15:22:55.387530",
            updatedBy        : "import"
    ]

    static Map doodiaTVEData = [
            elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9788223",
            depth        : 7,
            namePath     : "Plantae/Charophyta/Equisetopsida/Polypodiidae/Polypodiales/Blechnaceae/Doodia",
            parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9788187",
            taxonId      : 2910041,
            taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2910041",
            treeElementId: 9788223,
            treePath     : "/9787517/9787518/9787519/9787648/9787977/9788187/9788223",
            treeVersionId: 9787484
    ]

    static Map blechnaceaeElementData = [
            id               : 9788187,
            lockVersion      : 0,
            displayHtml      : "<data><scientific><name id='222592'><element class='Blechnaceae'>Blechnaceae</element> <authors><author id='8244' title='Newman, E.'>Newman</author></authors></name></scientific><citation>CHAH (2009), <i>Australian Plant Census</i></citation></data>",
            excluded         : false,
            instanceId       : 651382,
            instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/651382",
            nameElement      : "Blechnaceae",
            nameId           : 222592,
            nameLink         : "http://localhost:7070/nsl-mapper/name/apni/222592",
            previousElementId: null,
            profile          : ["APC Dist.": ["value": "WA, NT, SA, Qld, NSW, LHI, NI, ACT, Vic, Tas, MI", "created_at": "2009-10-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2009-10-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1111961"]],
            rank             : "Familia",
            simpleName       : "Blechnaceae",
            sourceElementLink: null,
            sourceShard      : "APNI",
            synonyms         : null,
            synonymsHtml     : "<synonyms></synonyms>",
            updatedAt        : "2018-01-01 15:22:55.387530",
            updatedBy        : "import"
    ]

    static Map blechnaceaeTVEData = [
            elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9788187",
            depth        : 6,
            namePath     : "Plantae/Charophyta/Equisetopsida/Polypodiidae/Polypodiales/Blechnaceae",
            parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9787977",
            taxonId      : 8032171,
            taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8032171",
            treeElementId: 9788187,
            treePath     : "/9787517/9787518/9787519/9787648/9787977/9788187",
            treeVersionId: 9787484
    ]

    static Map asperaElementData = [
            id               : 9788224,
            lockVersion      : 0,
            displayHtml      : "<data><scientific><name id='70944'><scientific><name id='70914'><element class='Doodia'>Doodia</element></name></scientific> <element class='aspera'>aspera</element> <authors><author id='1441' title='Brown, R.'>R.Br.</author></authors></name></scientific><citation>CHAH (2014), <i>Australian Plant Census</i></citation></data>",
            excluded         : false,
            instanceId       : 781104,
            instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/781104",
            nameElement      : "aspera",
            nameId           : 70944,
            nameLink         : "http://localhost:7070/nsl-mapper/name/apni/70944",
            previousElementId: null,
            profile          : ["APC Dist.": ["value": "Qld, NSW, LHI, NI, Vic, Tas", "created_at": "2014-03-25T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2014-03-25T14:04:06+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1132306"], "APC Comment": ["value": "Treated as <i>Blechnum neohollandicum</i> Christenh. in NSW.", "created_at": "2016-06-10T15:21:38.135+10:00", "created_by": "blepschi", "updated_at": "2016-06-10T15:21:38.135+10:00", "updated_by": "blepschi", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/6842405"]],
            rank             : "Species",
            simpleName       : "Doodia aspera",
            sourceElementLink: null,
            sourceShard      : "APNI",
            synonyms         : ["Woodwardia aspera": ["mis": false, "nom": true, "tax": false, "type": "nomenclatural synonym", "cites": "Mettenius, G.H. (1856), <i>Filices Horti Botanici Lipsiensis</i>", "name_id": 106698, "name_link": "http://localhost:7070/nsl-mapper/name/apni/106698", "full_name_html": "<scientific><name id='106698'><scientific><name id='106675'><element class='Woodwardia'>Woodwardia</element></name></scientific> <element class='aspera'>aspera</element> <authors>(<base id='1441' title='Brown, R.'>R.Br.</base>) <author id='7081' title='Mettenius, G.H.'>Mett.</author></authors></name></scientific>"], "Blechnum neohollandicum": ["mis": false, "nom": false, "tax": true, "type": "taxonomic synonym", "cites": "Christenhusz, M.J.M., Zhang, X.C. & Schneider, H. (2011), A linear sequence of extant families and genera of lycophytes and ferns. <i>Phytotaxa</i> 19", "name_id": 239547, "name_link": "http://localhost:7070/nsl-mapper/name/apni/239547", "full_name_html": "<scientific><name id='239547'><scientific><name id='56340'><element class='Blechnum'>Blechnum</element></name></scientific> <element class='neohollandicum'>neohollandicum</element> <authors><author id='6422' title='Christenhusz, M.J.M.'>Christenh.</author></authors></name></scientific>"], "Doodia aspera var. aspera": ["mis": false, "nom": true, "tax": false, "type": "nomenclatural synonym", "cites": "Bailey, F.M. (1881), <i>The fern world of Australia</i>", "name_id": 70967, "name_link": "http://localhost:7070/nsl-mapper/name/apni/70967", "full_name_html": "<scientific><name id='70967'><scientific><name id='70944'><scientific><name id='70914'><element class='Doodia'>Doodia</element></name></scientific> <element class='aspera'>aspera</element> <authors><author id='1441' title='Brown, R.'>R.Br.</author></authors></name></scientific> <rank id='54412'>var.</rank> <element class='aspera'>aspera</element></name></scientific>"], "Doodia aspera var. angustifrons": ["mis": false, "nom": false, "tax": true, "type": "taxonomic synonym", "cites": "Domin, K. (1915), Beitrage zur Flora und Pflanzengeographie Australiens. <i>Bibliotheca Botanica</i> 20(85)", "name_id": 70959, "name_link": "http://localhost:7070/nsl-mapper/name/apni/70959", "full_name_html": "<scientific><name id='70959'><scientific><name id='70944'><scientific><name id='70914'><element class='Doodia'>Doodia</element></name></scientific> <element class='aspera'>aspera</element></name></scientific> <rank id='54412'>var.</rank> <element class='angustifrons'>angustifrons</element> <authors><author id='6860' title='Domin, K.'>Domin</author></authors></name></scientific>"]],
            synonymsHtml     : "<synonyms><nom><scientific><name id='106698'><scientific><name id='106675'><element class='Woodwardia'>Woodwardia</element></name></scientific> <element class='aspera'>aspera</element> <authors>(<base id='1441' title='Brown, R.'>R.Br.</base>) <author id='7081' title='Mettenius, G.H.'>Mett.</author></authors></name></scientific> <type>nomenclatural synonym</type></nom><nom><scientific><name id='70967'><scientific><name id='70944'><scientific><name id='70914'><element class='Doodia'>Doodia</element></name></scientific> <element class='aspera'>aspera</element> <authors><author id='1441' title='Brown, R.'>R.Br.</author></authors></name></scientific> <rank id='54412'>var.</rank> <element class='aspera'>aspera</element></name></scientific> <type>nomenclatural synonym</type></nom><tax><scientific><name id='70959'><scientific><name id='70944'><scientific><name id='70914'><element class='Doodia'>Doodia</element></name></scientific> <element class='aspera'>aspera</element></name></scientific> <rank id='54412'>var.</rank> <element class='angustifrons'>angustifrons</element> <authors><author id='6860' title='Domin, K.'>Domin</author></authors></name></scientific> <type>taxonomic synonym</type></tax><tax><scientific><name id='239547'><scientific><name id='56340'><element class='Blechnum'>Blechnum</element></name></scientific> <element class='neohollandicum'>neohollandicum</element> <authors><author id='6422' title='Christenhusz, M.J.M.'>Christenh.</author></authors></name></scientific> <type>taxonomic synonym</type></tax></synonyms>",
            updatedAt        : "2018-01-01 15:22:55.387530",
            updatedBy        : "import"
    ]

    static Map asperaTVEData = [
            elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9788224",
            depth        : 8,
            namePath     : "Plantae/Charophyta/Equisetopsida/Polypodiidae/Polypodiales/Blechnaceae/Doodia/aspera",
            parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9788223",
            taxonId      : 2895769,
            taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2895769",
            treeElementId: 9788224,
            treePath     : "/9787517/9787518/9787519/9787648/9787977/9788187/9788223/9788224",
            treeVersionId: 9787484
    ]

    static List<Map> testTreeVersionElementData() {
        [
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9787517",
                        depth        : 1,
                        namePath     : "Plantae",
                        parentId     : null,
                        taxonId      : 9723412,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/9723412",
                        treeElementId: 9787517,
                        treePath     : "/9787517",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825378",
                        depth        : 2,
                        namePath     : "Plantae/Anthocerotophyta",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9787517",
                        taxonId      : 9434056,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/9434056",
                        treeElementId: 9825378,
                        treePath     : "/9787517/9825378",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825379",
                        depth        : 3,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825378",
                        taxonId      : 9434055,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/9434055",
                        treeElementId: 9825379,
                        treePath     : "/9787517/9825378/9825379",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825380",
                        depth        : 4,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825379",
                        taxonId      : 8513221,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8513221",
                        treeElementId: 9825380,
                        treePath     : "/9787517/9825378/9825379/9825380",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825381",
                        depth        : 5,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825380",
                        taxonId      : 8513220,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8513220",
                        treeElementId: 9825381,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825382",
                        depth        : 6,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825381",
                        taxonId      : 8513200,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8513200",
                        treeElementId: 9825382,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825383",
                        depth        : 7,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Anthoceros",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825382",
                        taxonId      : 6722223,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/6722223",
                        treeElementId: 9825383,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825383",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825384",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Anthoceros/capricornii",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825383",
                        taxonId      : 2910349,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2910349",
                        treeElementId: 9825384,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825383/9825384",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825385",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Anthoceros/ferdinandi-muelleri",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825383",
                        taxonId      : 2909847,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2909847",
                        treeElementId: 9825385,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825383/9825385",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825388",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Anthoceros/fragilis",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825383",
                        taxonId      : 2916003,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2916003",
                        treeElementId: 9825388,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825383/9825388",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825386",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Anthoceros/laminifer",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825383",
                        taxonId      : 2891332,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2891332",
                        treeElementId: 9825386,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825383/9825386",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825387",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Anthoceros/punctatus",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825383",
                        taxonId      : 2901206,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2901206",
                        treeElementId: 9825387,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825383/9825387",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825389",
                        depth        : 7,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Folioceros",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825382",
                        taxonId      : 2894485,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2894485",
                        treeElementId: 9825389,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825389",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825390",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Folioceros/fuciformis",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825389",
                        taxonId      : 2891695,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2891695",
                        treeElementId: 9825390,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825389/9825390",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825391",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Anthocerotidae/Anthocerotales/Anthocerotaceae/Folioceros/glandulosus",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825389",
                        taxonId      : 2896010,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2896010",
                        treeElementId: 9825391,
                        treePath     : "/9787517/9825378/9825379/9825380/9825381/9825382/9825389/9825391",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825408",
                        depth        : 4,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825379",
                        taxonId      : 8513224,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8513224",
                        treeElementId: 9825408,
                        treePath     : "/9787517/9825378/9825379/9825408",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825409",
                        depth        : 5,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825408",
                        taxonId      : 8513222,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8513222",
                        treeElementId: 9825409,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825410",
                        depth        : 6,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825409",
                        taxonId      : 8513219,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8513219",
                        treeElementId: 9825410,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825411",
                        depth        : 7,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825410",
                        taxonId      : 8513207,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8513207",
                        treeElementId: 9825411,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825412",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Dendroceros",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825411",
                        taxonId      : 2909398,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2909398",
                        treeElementId: 9825412,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825412",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825413",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Dendroceros/australis",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825412",
                        taxonId      : 2895623,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2895623",
                        treeElementId: 9825413,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825412/9825413",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825414",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Dendroceros/crispatus",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825412",
                        taxonId      : 2909090,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2909090",
                        treeElementId: 9825414,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825412/9825414",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825418",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Dendroceros/difficilis",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825412",
                        taxonId      : 2897137,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2897137",
                        treeElementId: 9825418,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825412/9825418",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825415",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Dendroceros/granulatus",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825412",
                        taxonId      : 2897129,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2897129",
                        treeElementId: 9825415,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825412/9825415",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825419",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Dendroceros/muelleri",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825412",
                        taxonId      : 2916733,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2916733",
                        treeElementId: 9825419,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825412/9825419",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825416",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Dendroceros/subtropicus",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825412",
                        taxonId      : 2917550,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2917550",
                        treeElementId: 9825416,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825412/9825416",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825417",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Dendroceros/wattsianus",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825412",
                        taxonId      : 2913739,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2913739",
                        treeElementId: 9825417,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825412/9825417",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825420",
                        depth        : 8,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Megaceros",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825411",
                        taxonId      : 8513209,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/8513209",
                        treeElementId: 9825420,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825420",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825421",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Megaceros/carnosus",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825420",
                        taxonId      : 2917526,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2917526",
                        treeElementId: 9825421,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825420/9825421",
                        treeVersionId: 9787484
                ],
                [
                        elementLink  : "http://localhost:7070/nsl-mapper/tree/9787484/9825422",
                        depth        : 9,
                        namePath     : "Plantae/Anthocerotophyta/Anthocerotopsida/Dendrocerotidae/Dendrocerotales/Dendrocerotaceae/Dendrocerotoideae/Megaceros/crassus",
                        parentId     : "http://localhost:7070/nsl-mapper/tree/9787484/9825420",
                        taxonId      : 2909144,
                        taxonLink    : "http://localhost:7070/nsl-mapper/node/apni/2909144",
                        treeElementId: 9825422,
                        treePath     : "/9787517/9825378/9825379/9825408/9825409/9825410/9825411/9825420/9825422",
                        treeVersionId: 9787484
                ]
        ]
    }


    static List<Map> testElementData() {
        [
                [
                        id               : 9787517,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='54717'><element class='Plantae'>Plantae</element> <authors><author id='3882' title='Haeckel, Ernst Heinrich Philipp August'>Haeckel</author></authors></name></scientific><citation>CHAH (2012), <i>Australian Plant Census</i></citation></data>",
                        excluded         : false,
                        instanceId       : 738442,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/738442",
                        nameElement      : "Plantae",
                        nameId           : 54717,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/54717",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Regnum",
                        simpleName       : "Plantae",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825378,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='238892'><element class='Anthocerotophyta'>Anthocerotophyta</element> <authors><ex id='7053' title='Rothmaler, W.H.P.'>Rothm.</ex> ex <author id='5307' title='Stotler,R.E. &amp; Crandall-Stotler,B.J.'>Stotler & Crand.-Stotl.</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8509445,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8509445",
                        nameElement      : "Anthocerotophyta",
                        nameId           : 238892,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/238892",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Division",
                        simpleName       : "Anthocerotophyta",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825379,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='238893'><element class='Anthocerotopsida'>Anthocerotopsida</element> <authors><ex id='2484' title='de Bary, H.A.'>de Bary</ex> ex <author id='3443' title='Janczewski, E. von G.'>Jancz.</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8509444,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8509444",
                        nameElement      : "Anthocerotopsida",
                        nameId           : 238893,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/238893",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Classis",
                        simpleName       : "Anthocerotopsida",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825380,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='240384'><element class='Anthocerotidae'>Anthocerotidae</element> <authors><author id='6453' title='Rosenvinge, J.L.A.K.'>Rosenv.</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8509443,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8509443",
                        nameElement      : "Anthocerotidae",
                        nameId           : 240384,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/240384",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Subclassis",
                        simpleName       : "Anthocerotidae",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825381,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='142301'><element class='Anthocerotales'>Anthocerotales</element> <authors><author id='2624' title='Limpricht, K.G.'>Limpr.</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8508886,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8508886",
                        nameElement      : "Anthocerotales",
                        nameId           : 142301,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/142301",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Ordo",
                        simpleName       : "Anthocerotales",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825382,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='124939'><element class='Anthocerotaceae'>Anthocerotaceae</element> <authors>(<base id='2041' title='Gray, S.F.'>Gray</base>) <author id='6855' title='Dumortier, B.C.J.'>Dumort.</author></authors></name></scientific><citation>CHAH (2011), <i>Australian Plant Census</i></citation></data>",
                        excluded         : false,
                        instanceId       : 748950,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/748950",
                        nameElement      : "Anthocerotaceae",
                        nameId           : 124939,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/124939",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "WA, NT, Qld, NSW, Vic, Tas", "created_at": "2012-05-21T00:00:00+10:00", "created_by": "KIRSTENC", "updated_at": "2012-05-21T00:00:00+10:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1124834"]],
                        rank             : "Familia",
                        simpleName       : "Anthocerotaceae",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825383,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element> <authors><author id='1426' title='Linnaeus, C.'>L.</author></authors></name></scientific><citation>CHAH (2010), <i>Australian Plant Census</i></citation></data>",
                        excluded         : false,
                        instanceId       : 668637,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/668637",
                        nameElement      : "Anthoceros",
                        nameId           : 121601,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/121601",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "WA, NT, SA, Qld, NSW, ACT, Vic, Tas", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117116"]],
                        rank             : "Genus",
                        simpleName       : "Anthoceros",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825384,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='144273'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='capricornii'>capricornii</element> <authors><author id='1771' title='Cargill, D.C. &amp; Scott, G.A.M.'>Cargill & G.A.M.Scott</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 621662,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/621662",
                        nameElement      : "capricornii",
                        nameId           : 144273,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/144273",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "WA, NT", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117117"]],
                        rank             : "Species",
                        simpleName       : "Anthoceros capricornii",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : ["Anthoceros adscendens": ["mis": true, "nom": false, "tax": false, "type": "pro parte misapplied", "cites": "Lehmann, J.G.C. & Lindenberg, J.B.W. in Lehmann, J.G.C. (1832), <i>Novarum et Minus Cognitarum Stirpium Pugillus</i> 4", "name_id": 162382, "name_link": "http://localhost:7070/nsl-mapper/name/apni/162382", "full_name_html": "<scientific><name id='162382'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='adscendens'>adscendens</element> <authors><author id='1628' title='Lehmann, J.G.C. &amp; Lindenberg, J.B.W.'>Lehm. & Lindenb.</author></authors></name></scientific>"]],
                        synonymsHtml     : "<synonyms><mis><scientific><name id='162382'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='adscendens'>adscendens</element> <authors><author id='1628' title='Lehmann, J.G.C. &amp; Lindenberg, J.B.W.'>Lehm. & Lindenb.</author></authors></name></scientific> <type>pro parte misapplied</type> by <citation>Lehmann, J.G.C. & Lindenberg, J.B.W. in Lehmann, J.G.C. (1832), <i>Novarum et Minus Cognitarum Stirpium Pugillus</i> 4</citation></mis></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825385,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='209869'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='ferdinandi-muelleri'>ferdinandi-muelleri</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 621668,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/621668",
                        nameElement      : "ferdinandi-muelleri",
                        nameId           : 209869,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/209869",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "?Qld", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117118"]],
                        rank             : "Species",
                        simpleName       : "Anthoceros ferdinandi-muelleri",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825388,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='142232'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='fragilis'>fragilis</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>Cargill, D.C., Söderström, L., Hagborg, A. & Konrat, M. von (2013), Notes on Early Land Plants Today. 23. A new synonym in Anthoceros (Anthocerotaceae, Anthocerotophyta). <i>Phytotaxa</i> 76(3)</citation></data>",
                        excluded         : false,
                        instanceId       : 760852,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/760852",
                        nameElement      : "fragilis",
                        nameId           : 142232,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/142232",
                        previousElementId: null,
                        profile          : ["Type": ["value": "Australia. Queensland: Amalie Dietrich (holotype G-61292! [=G-24322!]).", "created_at": "2013-01-16T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2013-01-16T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1086559"], "APC Dist.": ["value": "Qld", "created_at": "2013-02-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2013-02-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1128261"]],
                        rank             : "Species",
                        simpleName       : "Anthoceros fragilis",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : ["Anthoceros fertilis": ["mis": false, "nom": false, "tax": true, "type": "taxonomic synonym", "cites": "Stephani, F. (1916), <i>Species Hepaticarum</i> 5", "name_id": 209870, "name_link": "http://localhost:7070/nsl-mapper/name/apni/209870", "full_name_html": "<scientific><name id='209870'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='fertilis'>fertilis</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific>"]],
                        synonymsHtml     : "<synonyms><tax><scientific><name id='209870'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='fertilis'>fertilis</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific> <type>taxonomic synonym</type></tax></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825386,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='202233'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='laminifer'>laminifer</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 621709,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/621709",
                        nameElement      : "laminifer",
                        nameId           : 202233,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/202233",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117121"]],
                        rank             : "Species",
                        simpleName       : "Anthoceros laminifer",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825387,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='122138'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='punctatus'>punctatus</element> <authors><author id='1426' title='Linnaeus, C.'>L.</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 621713,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/621713",
                        nameElement      : "punctatus",
                        nameId           : 122138,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/122138",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "SA, Qld, NSW, ACT, Vic, Tas", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117122"]],
                        rank             : "Species",
                        simpleName       : "Anthoceros punctatus",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825389,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='134990'><element class='Folioceros'>Folioceros</element> <authors><author id='1941' title='Bhardwaj, D.C.'>D.C.Bhardwaj</author></authors></name></scientific><citation>CHAH (2010), <i>Australian Plant Census</i></citation></data>",
                        excluded         : false,
                        instanceId       : 669233,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/669233",
                        nameElement      : "Folioceros",
                        nameId           : 134990,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/134990",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld, NSW", "created_at": "2011-01-31T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-31T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117130"]],
                        rank             : "Genus",
                        simpleName       : "Folioceros",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825390,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='143486'><scientific><name id='134990'><element class='Folioceros'>Folioceros</element></name></scientific> <element class='fuciformis'>fuciformis</element> <authors>(<base id='8996' title='Montagne, J.P.F.C.'>Mont.</base>) <author id='1941' title='Bhardwaj, D.C.'>D.C.Bhardwaj</author></authors></name></scientific><citation>Bhardwaj, D.C. (1975), <i>Geophytology</i> 5</citation></data>",
                        excluded         : false,
                        instanceId       : 621673,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/621673",
                        nameElement      : "fuciformis",
                        nameId           : 143486,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/143486",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld", "created_at": "2011-01-31T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-31T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117131"]],
                        rank             : "Species",
                        simpleName       : "Folioceros fuciformis",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : ["Anthoceros fuciformis": ["mis": false, "nom": true, "tax": false, "type": "basionym", "cites": "Montagne, J.P.F.C. (1843), <i>Annales des Sciences Naturelles; Botanique</i> 20", "name_id": 142253, "name_link": "http://localhost:7070/nsl-mapper/name/apni/142253", "full_name_html": "<scientific><name id='142253'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='fuciformis'>fuciformis</element> <authors><author id='8996' title='Montagne, J.P.F.C.'>Mont.</author></authors></name></scientific>"]],
                        synonymsHtml     : "<synonyms><nom><scientific><name id='142253'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='fuciformis'>fuciformis</element> <authors><author id='8996' title='Montagne, J.P.F.C.'>Mont.</author></authors></name></scientific> <type>basionym</type></nom></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825391,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='134991'><scientific><name id='134990'><element class='Folioceros'>Folioceros</element></name></scientific> <element class='glandulosus'>glandulosus</element> <authors>(<base id='1628' title='Lehmann, J.G.C. &amp; Lindenberg, J.B.W.'>Lehm. & Lindenb.</base>) <author id='1941' title='Bhardwaj, D.C.'>D.C.Bhardwaj</author></authors></name></scientific><citation>CHAH (2010), <i>Australian Plant Census</i></citation></data>",
                        excluded         : false,
                        instanceId       : 669234,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/669234",
                        nameElement      : "glandulosus",
                        nameId           : 134991,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/134991",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "NSW", "created_at": "2011-01-31T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-31T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117132"]],
                        rank             : "Species",
                        simpleName       : "Folioceros glandulosus",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : ["Anthoceros glandulosus": ["mis": false, "nom": true, "tax": false, "type": "nomenclatural synonym", "cites": "Lehmann, J.G.C. & Lindenberg, J.B.W. in Lehmann, J.G.C. (1832), <i>Novarum et Minus Cognitarum Stirpium Pugillus</i> 4", "name_id": 129589, "name_link": "http://localhost:7070/nsl-mapper/name/apni/129589", "full_name_html": "<scientific><name id='129589'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='glandulosus'>glandulosus</element> <authors><author id='1628' title='Lehmann, J.G.C. &amp; Lindenberg, J.B.W.'>Lehm. & Lindenb.</author></authors></name></scientific>"], "Aspiromitus glandulosus": ["mis": false, "nom": true, "tax": false, "type": "nomenclatural synonym", "cites": "Stephani, F. (1916), <i>Species Hepaticarum</i> 5", "name_id": 209879, "name_link": "http://localhost:7070/nsl-mapper/name/apni/209879", "full_name_html": "<scientific><name id='209879'><scientific><name id='172172'><element class='Aspiromitus'>Aspiromitus</element></name></scientific> <element class='glandulosus'>glandulosus</element> <authors>(<base id='1628' title='Lehmann, J.G.C. &amp; Lindenberg, J.B.W.'>Lehm. & Lindenb.</base>) <author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific>"]],
                        synonymsHtml     : "<synonyms><nom><scientific><name id='129589'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='glandulosus'>glandulosus</element> <authors><author id='1628' title='Lehmann, J.G.C. &amp; Lindenberg, J.B.W.'>Lehm. & Lindenb.</author></authors></name></scientific> <type>nomenclatural synonym</type></nom><nom><scientific><name id='209879'><scientific><name id='172172'><element class='Aspiromitus'>Aspiromitus</element></name></scientific> <element class='glandulosus'>glandulosus</element> <authors>(<base id='1628' title='Lehmann, J.G.C. &amp; Lindenberg, J.B.W.'>Lehm. & Lindenb.</base>) <author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific> <type>nomenclatural synonym</type></nom></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825408,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='240391'><element class='Dendrocerotidae'>Dendrocerotidae</element> <authors><author id='5261' title='Duff, R.J., Villarreal, J.C., Cargill, D.C. &amp; Renzaglia, K.S.'>Duff, J.C.Villarreal, Cargill & Renzaglia</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8511897,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8511897",
                        nameElement      : "Dendrocerotidae",
                        nameId           : 240391,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/240391",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Subclassis",
                        simpleName       : "Dendrocerotidae",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825409,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='240393'><element class='Dendrocerotales'>Dendrocerotales</element> <authors><author id='3432' title='H&auml;ssel de Men&eacute;ndez, G.G.'>Hässel</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8512151,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8512151",
                        nameElement      : "Dendrocerotales",
                        nameId           : 240393,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/240393",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Ordo",
                        simpleName       : "Dendrocerotales",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825410,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='193461'><element class='Dendrocerotaceae'>Dendrocerotaceae</element> <authors>(<base id='2276' title='Milde, C.A.J.'>Milde</base>) <author id='3432' title='H&auml;ssel de Men&eacute;ndez, G.G.'>Hässel</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8512407,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8512407",
                        nameElement      : "Dendrocerotaceae",
                        nameId           : 193461,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/193461",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Familia",
                        simpleName       : "Dendrocerotaceae",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825411,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='240394'><scientific><name id='193461'><element class='Dendrocerotaceae'>Dendrocerotaceae</element></name></scientific> <element class='Dendrocerotoideae'>Dendrocerotoideae</element> <authors><author id='1751' title='Schuster, R.M.'>R.M.Schust.</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8512665,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8512665",
                        nameElement      : "Dendrocerotoideae",
                        nameId           : 240394,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/240394",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Subfamilia",
                        simpleName       : "Dendrocerotaceae Dendrocerotoideae",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825412,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element> <authors><author id='6893' title='Nees von Esenbeck, C.G.D.'>Nees</author></authors></name></scientific><citation>CHAH (2010), <i>Australian Plant Census</i></citation></data>",
                        excluded         : false,
                        instanceId       : 668662,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/668662",
                        nameElement      : "Dendroceros",
                        nameId           : 129597,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/129597",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld, NSW", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117123"]],
                        rank             : "Genus",
                        simpleName       : "Dendroceros",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825413,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='210308'><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element></name></scientific> <element class='australis'>australis</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 622818,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/622818",
                        nameElement      : "australis",
                        nameId           : 210308,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/210308",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "NSW", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117124"]],
                        rank             : "Species",
                        simpleName       : "Dendroceros australis",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825414,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='178505'><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element></name></scientific> <element class='crispatus'>crispatus</element> <authors>(<base id='6851' title='Hooker, W.J.'>Hook.</base>) <author id='6893' title='Nees von Esenbeck, C.G.D.'>Nees</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 622823,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/622823",
                        nameElement      : "crispatus",
                        nameId           : 178505,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/178505",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117125"]],
                        rank             : "Species",
                        simpleName       : "Dendroceros crispatus",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : ["Monoclea crispata": ["mis": false, "nom": true, "tax": false, "type": "nomenclatural synonym", "cites": "Hooker, W.J. in Hooker, W.J. (ed.) (1830), <i>Botanical Miscellany</i> 1", "name_id": 210309, "name_link": "http://localhost:7070/nsl-mapper/name/apni/210309", "full_name_html": "<scientific><name id='210309'><scientific><name id='133731'><element class='Monoclea'>Monoclea</element></name></scientific> <element class='crispata'>crispata</element> <authors><author id='6851' title='Hooker, W.J.'>Hook.</author></authors></name></scientific>"]],
                        synonymsHtml     : "<synonyms><nom><scientific><name id='210309'><scientific><name id='133731'><element class='Monoclea'>Monoclea</element></name></scientific> <element class='crispata'>crispata</element> <authors><author id='6851' title='Hooker, W.J.'>Hook.</author></authors></name></scientific> <type>nomenclatural synonym</type></nom></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825418,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='210317'><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element></name></scientific> <element class='difficilis'>difficilis</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>Pócs, T. & Streimann, H. (1999), Epiphyllous liverworts from Queensland, Australia. <i>Bryobrothera</i> 5</citation></data>",
                        excluded         : false,
                        instanceId       : 622849,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/622849",
                        nameElement      : "difficilis",
                        nameId           : 210317,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/210317",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "BLEPSCHI", "updated_at": "2013-10-24T12:18:26+11:00", "updated_by": "BLEPSCHI", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1131154"], "APC Comment": ["value": "Listed as \"<i>Dendroceros</i> cf. <i>difficilis</i>\" by P.M.McCarthy, <i>Checkl. Austral. Liverworts and Hornworts</i> 35 (2003).", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "BLEPSCHI", "updated_at": "2013-10-24T12:18:26+11:00", "updated_by": "BLEPSCHI", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1131153"]],
                        rank             : "Species",
                        simpleName       : "Dendroceros difficilis",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825415,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='210311'><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element></name></scientific> <element class='granulatus'>granulatus</element> <authors><author id='1465' title='Mitten, W.'>Mitt.</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 622830,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/622830",
                        nameElement      : "granulatus",
                        nameId           : 210311,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/210311",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117126"]],
                        rank             : "Species",
                        simpleName       : "Dendroceros granulatus",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825419,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='210313'><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element></name></scientific> <element class='muelleri'>muelleri</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>CHAH (2010), <i>Australian Plant Census</i></citation></data>",
                        excluded         : false,
                        instanceId       : 772246,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/772246",
                        nameElement      : "muelleri",
                        nameId           : 210313,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/210313",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld, NSW", "created_at": "2013-10-24T00:00:00+11:00", "created_by": "BLEPSCHI", "updated_at": "2013-10-24T11:42:28+11:00", "updated_by": "BLEPSCHI", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1131152"]],
                        rank             : "Species",
                        simpleName       : "Dendroceros muelleri",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : ["Dendroceros ferdinandi-muelleri": ["mis": false, "nom": false, "tax": false, "type": "orthographic variant", "cites": "Stephani, F. (1916), <i>Species Hepaticarum</i> 5", "name_id": 210312, "name_link": "http://localhost:7070/nsl-mapper/name/apni/210312", "full_name_html": "<scientific><name id='210312'><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element></name></scientific> <element class='ferdinandi-muelleri'>ferdinandi-muelleri</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific>"]],
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825416,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='210314'><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element></name></scientific> <element class='subtropicus'>subtropicus</element> <authors><author id='3814' title='Wild, C.J.'>C.J.Wild</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 622837,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/622837",
                        nameElement      : "subtropicus",
                        nameId           : 210314,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/210314",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Qld", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117127"]],
                        rank             : "Species",
                        simpleName       : "Dendroceros subtropicus",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825417,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='210315'><scientific><name id='129597'><element class='Dendroceros'>Dendroceros</element></name></scientific> <element class='wattsianus'>wattsianus</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 622841,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/622841",
                        nameElement      : "wattsianus",
                        nameId           : 210315,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/210315",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "NSW", "created_at": "2011-01-27T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-27T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117128"]],
                        rank             : "Species",
                        simpleName       : "Dendroceros wattsianus",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825420,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='124930'><element class='Megaceros'>Megaceros</element> <authors><author id='9964' title='Campbell, D.H.'>Campb.</author></authors></name></scientific><citation>Renzaglia, K.S., Villarreal, J.C. & Duff, R.J. in Goffinet, B. & Shaw, A.J. (ed.) (2009), New insights into morphology, anatomy and systematics of hornworts. <i>Bryophyte Biology</i> Edn. 2</citation></data>",
                        excluded         : false,
                        instanceId       : 8513196,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/8513196",
                        nameElement      : "Megaceros",
                        nameId           : 124930,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/124930",
                        previousElementId: null,
                        profile          : null,
                        rank             : "Genus",
                        simpleName       : "Megaceros",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825421,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='175653'><scientific><name id='124930'><element class='Megaceros'>Megaceros</element></name></scientific> <element class='carnosus'>carnosus</element> <authors>(<base id='1435' title='Stephani, F.'>Steph.</base>) <author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 624477,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/624477",
                        nameElement      : "carnosus",
                        nameId           : 175653,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/175653",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "NSW, Vic, Tas", "created_at": "2011-01-31T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-31T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117134"]],
                        rank             : "Species",
                        simpleName       : "Megaceros carnosus",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : ["Anthoceros carnosus": ["mis": false, "nom": true, "tax": false, "type": "nomenclatural synonym", "cites": "Stephani, F. (1889), Hepaticae Australiae. <i>Hedwigia</i> 28", "name_id": 175654, "name_link": "http://localhost:7070/nsl-mapper/name/apni/175654", "full_name_html": "<scientific><name id='175654'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='carnosus'>carnosus</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific>"]],
                        synonymsHtml     : "<synonyms><nom><scientific><name id='175654'><scientific><name id='121601'><element class='Anthoceros'>Anthoceros</element></name></scientific> <element class='carnosus'>carnosus</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific> <type>nomenclatural synonym</type></nom></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ],
                [
                        id               : 9825422,
                        lockVersion      : 0,
                        displayHtml      : "<data><scientific><name id='210888'><scientific><name id='124930'><element class='Megaceros'>Megaceros</element></name></scientific> <element class='crassus'>crassus</element> <authors><author id='1435' title='Stephani, F.'>Steph.</author></authors></name></scientific><citation>McCarthy, P.M. (2003), <i>Catalogue of Australian Liverworts and Hornworts</i></citation></data>",
                        excluded         : false,
                        instanceId       : 624478,
                        instanceLink     : "http://localhost:7070/nsl-mapper/instance/apni/624478",
                        nameElement      : "crassus",
                        nameId           : 210888,
                        nameLink         : "http://localhost:7070/nsl-mapper/name/apni/210888",
                        previousElementId: null,
                        profile          : ["APC Dist.": ["value": "Tas", "created_at": "2011-01-31T00:00:00+11:00", "created_by": "KIRSTENC", "updated_at": "2011-01-31T00:00:00+11:00", "updated_by": "KIRSTENC", "source_link": "http://localhost:7070/nsl-mapper/instanceNote/apni/1117135"]],
                        rank             : "Species",
                        simpleName       : "Megaceros crassus",
                        sourceElementLink: null,
                        sourceShard      : "APNI",
                        synonyms         : null,
                        synonymsHtml     : "<synonyms></synonyms>",
                        updatedAt        : "2018-01-01 15:22:55.387530",
                        updatedBy        : "import"
                ]
        ]
    }
}